---
- apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: install mysql-server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python-mysqldb
  notify: start mysql

- name: iptables allow 3306
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: 3306
    jump: ACCEPT
