---
- name: install apache2 - php
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - apache2-utils
    - php5
    - libapache2-mod-php5
    - php5-mysql
    - php5-cli
    - php5-cgi
    - php5-gd
  notify:
    - start apache
  when: ansible_os_family == 'Debian'
